Add workflow solo-dev-pr-approve.yaml chunk 3 'check-review-count'

diff --git a/.github/workflows/solo-dev-pr-approve.yaml b/.github/workflows/solo-dev-pr-approve.yaml
--- a/.github/workflows/solo-dev-pr-approve.yaml
+++ b/.github/workflows/solo-dev-pr-approve.yaml
@@ -69,3 +69,28 @@ jobs:
           else
             echo "PR is ready for review!"
           fi
+  check-reviewer-count:
+    runs-on: ubuntu-latest
+    needs: pr-readiness-check
+    steps:
+      - name: Check out the repository
+        uses: actions/checkout@v4
+      - name: Get the number of reviewers
+        id: reviewer-count
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |-
+          REVIEWERS=$(gh api -H "Accept: application/vnd.github+json" \
+            "/repos/${{ github.repository }}/collaborators?affiliation=direct" \
+            --jq '[.[] | select(.permissions.push == true)] | length')
+          echo "REVIEWER_COUNT=$REVIEWERS" >> "$GITHUB_ENV"
+      - name: Validate reviewer count
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |-
+          if [[ "$REVIEWER_COUNT" -gt 1 ]]; then
+            echo "There are multiple reviewers. Manual review is required."
+            exit 1
+          else
+            echo "Solo developer detected. Proceeding with auto-approval."
+          fi
